# Generated by Django 4.0.6 on 2022-07-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='creator',
            new_name='owner',
        ),
    ]
